import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../../services/api';
import { Card, ErrorBox } from '../../components/Ui';

function Auth({ title, submit, fields, setFields, error, button = 'Register', register, children }) {
  return <div className="auth-page"><Card><div className="brand auth-brand">dinora <span>/ admin</span></div><h1>{title}</h1><form onSubmit={submit} className="form-grid">{register && <label>Name<input required value={fields.name} onChange={(e) => setFields({ ...fields, name: e.target.value })} /></label>}<label>Email<input required type="email" value={fields.email} onChange={(e) => setFields({ ...fields, email: e.target.value })} /></label><label>Password<input required minLength="6" type="password" value={fields.password} onChange={(e) => setFields({ ...fields, password: e.target.value })} /></label><button className="btn primary">{button}</button></form><ErrorBox error={error} /><p className="center">{children}</p></Card></div>;
}
export function AdminLogin() { const navigate = useNavigate(); const [fields,setFields] = useState({email:'',password:''}); const [error,setError] = useState(''); const submit = async (event) => { event.preventDefault(); try { const data = await api.login(fields); localStorage.setItem('dinora-admin-token', data.token); localStorage.setItem('dinora-admin-user', JSON.stringify(data.user)); navigate('/admin/dashboard'); } catch (err) { setError(err.message); } }; return <Auth title="Admin login" submit={submit} fields={fields} setFields={setFields} error={error} button="Login"><Link to="/admin/register">Create admin account</Link></Auth>; }
export function AdminRegister() { const navigate = useNavigate(); const [fields,setFields] = useState({name:'',email:'',password:''}); const [error,setError] = useState(''); const submit = async (event) => { event.preventDefault(); try { const data = await api.register(fields); localStorage.setItem('dinora-admin-token', data.token); localStorage.setItem('dinora-admin-user', JSON.stringify(data.user)); navigate('/admin/dashboard'); } catch (err) { setError(err.message); } }; return <Auth title="Create admin account" submit={submit} fields={fields} setFields={setFields} error={error} register><Link to="/admin/login">Already have an account?</Link></Auth>; }
